/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/kit';

export type BaseFeeConfig = {
  cliffFeeNumerator: bigint;
  periodFrequency: bigint;
  reductionFactor: bigint;
  numberOfPeriod: number;
  feeSchedulerMode: number;
  padding0: ReadonlyUint8Array;
};

export type BaseFeeConfigArgs = {
  cliffFeeNumerator: number | bigint;
  periodFrequency: number | bigint;
  reductionFactor: number | bigint;
  numberOfPeriod: number;
  feeSchedulerMode: number;
  padding0: ReadonlyUint8Array;
};

export function getBaseFeeConfigEncoder(): Encoder<BaseFeeConfigArgs> {
  return getStructEncoder([
    ['cliffFeeNumerator', getU64Encoder()],
    ['periodFrequency', getU64Encoder()],
    ['reductionFactor', getU64Encoder()],
    ['numberOfPeriod', getU16Encoder()],
    ['feeSchedulerMode', getU8Encoder()],
    ['padding0', fixEncoderSize(getBytesEncoder(), 5)],
  ]);
}

export function getBaseFeeConfigDecoder(): Decoder<BaseFeeConfig> {
  return getStructDecoder([
    ['cliffFeeNumerator', getU64Decoder()],
    ['periodFrequency', getU64Decoder()],
    ['reductionFactor', getU64Decoder()],
    ['numberOfPeriod', getU16Decoder()],
    ['feeSchedulerMode', getU8Decoder()],
    ['padding0', fixDecoderSize(getBytesDecoder(), 5)],
  ]);
}

export function getBaseFeeConfigCodec(): Codec<
  BaseFeeConfigArgs,
  BaseFeeConfig
> {
  return combineCodec(getBaseFeeConfigEncoder(), getBaseFeeConfigDecoder());
}
