/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtCurveComplete = {
  pool: Address;
  config: Address;
  baseReserve: bigint;
  quoteReserve: bigint;
};

export type EvtCurveCompleteArgs = {
  pool: Address;
  config: Address;
  baseReserve: number | bigint;
  quoteReserve: number | bigint;
};

export function getEvtCurveCompleteEncoder(): Encoder<EvtCurveCompleteArgs> {
  return getStructEncoder([
    ['pool', getAddressEncoder()],
    ['config', getAddressEncoder()],
    ['baseReserve', getU64Encoder()],
    ['quoteReserve', getU64Encoder()],
  ]);
}

export function getEvtCurveCompleteDecoder(): Decoder<EvtCurveComplete> {
  return getStructDecoder([
    ['pool', getAddressDecoder()],
    ['config', getAddressDecoder()],
    ['baseReserve', getU64Decoder()],
    ['quoteReserve', getU64Decoder()],
  ]);
}

export function getEvtCurveCompleteCodec(): Codec<
  EvtCurveCompleteArgs,
  EvtCurveComplete
> {
  return combineCodec(
    getEvtCurveCompleteEncoder(),
    getEvtCurveCompleteDecoder()
  );
}
