/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtCreateMeteoraMigrationMetadata = { virtualPool: Address };

export type EvtCreateMeteoraMigrationMetadataArgs =
  EvtCreateMeteoraMigrationMetadata;

export function getEvtCreateMeteoraMigrationMetadataEncoder(): Encoder<EvtCreateMeteoraMigrationMetadataArgs> {
  return getStructEncoder([['virtualPool', getAddressEncoder()]]);
}

export function getEvtCreateMeteoraMigrationMetadataDecoder(): Decoder<EvtCreateMeteoraMigrationMetadata> {
  return getStructDecoder([['virtualPool', getAddressDecoder()]]);
}

export function getEvtCreateMeteoraMigrationMetadataCodec(): Codec<
  EvtCreateMeteoraMigrationMetadataArgs,
  EvtCreateMeteoraMigrationMetadata
> {
  return combineCodec(
    getEvtCreateMeteoraMigrationMetadataEncoder(),
    getEvtCreateMeteoraMigrationMetadataDecoder()
  );
}
