/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtClaimTradingFee = {
  pool: Address;
  tokenBaseAmount: bigint;
  tokenQuoteAmount: bigint;
};

export type EvtClaimTradingFeeArgs = {
  pool: Address;
  tokenBaseAmount: number | bigint;
  tokenQuoteAmount: number | bigint;
};

export function getEvtClaimTradingFeeEncoder(): Encoder<EvtClaimTradingFeeArgs> {
  return getStructEncoder([
    ['pool', getAddressEncoder()],
    ['tokenBaseAmount', getU64Encoder()],
    ['tokenQuoteAmount', getU64Encoder()],
  ]);
}

export function getEvtClaimTradingFeeDecoder(): Decoder<EvtClaimTradingFee> {
  return getStructDecoder([
    ['pool', getAddressDecoder()],
    ['tokenBaseAmount', getU64Decoder()],
    ['tokenQuoteAmount', getU64Decoder()],
  ]);
}

export function getEvtClaimTradingFeeCodec(): Codec<
  EvtClaimTradingFeeArgs,
  EvtClaimTradingFee
> {
  return combineCodec(
    getEvtClaimTradingFeeEncoder(),
    getEvtClaimTradingFeeDecoder()
  );
}
