/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtClaimProtocolFee = {
  pool: Address;
  tokenBaseAmount: bigint;
  tokenQuoteAmount: bigint;
};

export type EvtClaimProtocolFeeArgs = {
  pool: Address;
  tokenBaseAmount: number | bigint;
  tokenQuoteAmount: number | bigint;
};

export function getEvtClaimProtocolFeeEncoder(): Encoder<EvtClaimProtocolFeeArgs> {
  return getStructEncoder([
    ['pool', getAddressEncoder()],
    ['tokenBaseAmount', getU64Encoder()],
    ['tokenQuoteAmount', getU64Encoder()],
  ]);
}

export function getEvtClaimProtocolFeeDecoder(): Decoder<EvtClaimProtocolFee> {
  return getStructDecoder([
    ['pool', getAddressDecoder()],
    ['tokenBaseAmount', getU64Decoder()],
    ['tokenQuoteAmount', getU64Decoder()],
  ]);
}

export function getEvtClaimProtocolFeeCodec(): Codec<
  EvtClaimProtocolFeeArgs,
  EvtClaimProtocolFee
> {
  return combineCodec(
    getEvtClaimProtocolFeeEncoder(),
    getEvtClaimProtocolFeeDecoder()
  );
}
