/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

/** Close claim fee operator */
export type EvtCloseClaimFeeOperator = {
  claimFeeOperator: Address;
  operator: Address;
};

export type EvtCloseClaimFeeOperatorArgs = EvtCloseClaimFeeOperator;

export function getEvtCloseClaimFeeOperatorEncoder(): Encoder<EvtCloseClaimFeeOperatorArgs> {
  return getStructEncoder([
    ['claimFeeOperator', getAddressEncoder()],
    ['operator', getAddressEncoder()],
  ]);
}

export function getEvtCloseClaimFeeOperatorDecoder(): Decoder<EvtCloseClaimFeeOperator> {
  return getStructDecoder([
    ['claimFeeOperator', getAddressDecoder()],
    ['operator', getAddressDecoder()],
  ]);
}

export function getEvtCloseClaimFeeOperatorCodec(): Codec<
  EvtCloseClaimFeeOperatorArgs,
  EvtCloseClaimFeeOperator
> {
  return combineCodec(
    getEvtCloseClaimFeeOperatorEncoder(),
    getEvtCloseClaimFeeOperatorDecoder()
  );
}
