/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

/** Create claim fee operator */
export type EvtCreateClaimFeeOperator = { operator: Address };

export type EvtCreateClaimFeeOperatorArgs = EvtCreateClaimFeeOperator;

export function getEvtCreateClaimFeeOperatorEncoder(): Encoder<EvtCreateClaimFeeOperatorArgs> {
  return getStructEncoder([['operator', getAddressEncoder()]]);
}

export function getEvtCreateClaimFeeOperatorDecoder(): Decoder<EvtCreateClaimFeeOperator> {
  return getStructDecoder([['operator', getAddressDecoder()]]);
}

export function getEvtCreateClaimFeeOperatorCodec(): Codec<
  EvtCreateClaimFeeOperatorArgs,
  EvtCreateClaimFeeOperator
> {
  return combineCodec(
    getEvtCreateClaimFeeOperatorEncoder(),
    getEvtCreateClaimFeeOperatorDecoder()
  );
}
