/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtInitializePool = {
  pool: Address;
  config: Address;
  creator: Address;
  baseMint: Address;
  poolType: number;
  activationPoint: bigint;
};

export type EvtInitializePoolArgs = {
  pool: Address;
  config: Address;
  creator: Address;
  baseMint: Address;
  poolType: number;
  activationPoint: number | bigint;
};

export function getEvtInitializePoolEncoder(): Encoder<EvtInitializePoolArgs> {
  return getStructEncoder([
    ['pool', getAddressEncoder()],
    ['config', getAddressEncoder()],
    ['creator', getAddressEncoder()],
    ['baseMint', getAddressEncoder()],
    ['poolType', getU8Encoder()],
    ['activationPoint', getU64Encoder()],
  ]);
}

export function getEvtInitializePoolDecoder(): Decoder<EvtInitializePool> {
  return getStructDecoder([
    ['pool', getAddressDecoder()],
    ['config', getAddressDecoder()],
    ['creator', getAddressDecoder()],
    ['baseMint', getAddressDecoder()],
    ['poolType', getU8Decoder()],
    ['activationPoint', getU64Decoder()],
  ]);
}

export function getEvtInitializePoolCodec(): Codec<
  EvtInitializePoolArgs,
  EvtInitializePool
> {
  return combineCodec(
    getEvtInitializePoolEncoder(),
    getEvtInitializePoolDecoder()
  );
}
