/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtProtocolWithdrawSurplus = {
  pool: Address;
  surplusAmount: bigint;
};

export type EvtProtocolWithdrawSurplusArgs = {
  pool: Address;
  surplusAmount: number | bigint;
};

export function getEvtProtocolWithdrawSurplusEncoder(): Encoder<EvtProtocolWithdrawSurplusArgs> {
  return getStructEncoder([
    ['pool', getAddressEncoder()],
    ['surplusAmount', getU64Encoder()],
  ]);
}

export function getEvtProtocolWithdrawSurplusDecoder(): Decoder<EvtProtocolWithdrawSurplus> {
  return getStructDecoder([
    ['pool', getAddressDecoder()],
    ['surplusAmount', getU64Decoder()],
  ]);
}

export function getEvtProtocolWithdrawSurplusCodec(): Codec<
  EvtProtocolWithdrawSurplusArgs,
  EvtProtocolWithdrawSurplus
> {
  return combineCodec(
    getEvtProtocolWithdrawSurplusEncoder(),
    getEvtProtocolWithdrawSurplusDecoder()
  );
}
