/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type EvtPartnerWithdrawSurplus = {
  pool: Address;
  surplusAmount: bigint;
};

export type EvtPartnerWithdrawSurplusArgs = {
  pool: Address;
  surplusAmount: number | bigint;
};

export function getEvtPartnerWithdrawSurplusEncoder(): Encoder<EvtPartnerWithdrawSurplusArgs> {
  return getStructEncoder([
    ['pool', getAddressEncoder()],
    ['surplusAmount', getU64Encoder()],
  ]);
}

export function getEvtPartnerWithdrawSurplusDecoder(): Decoder<EvtPartnerWithdrawSurplus> {
  return getStructDecoder([
    ['pool', getAddressDecoder()],
    ['surplusAmount', getU64Decoder()],
  ]);
}

export function getEvtPartnerWithdrawSurplusCodec(): Codec<
  EvtPartnerWithdrawSurplusArgs,
  EvtPartnerWithdrawSurplus
> {
  return combineCodec(
    getEvtPartnerWithdrawSurplusEncoder(),
    getEvtPartnerWithdrawSurplusDecoder()
  );
}
