/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type LiquidityDistributionParameters = {
  sqrtPrice: bigint;
  liquidity: bigint;
};

export type LiquidityDistributionParametersArgs = {
  sqrtPrice: number | bigint;
  liquidity: number | bigint;
};

export function getLiquidityDistributionParametersEncoder(): Encoder<LiquidityDistributionParametersArgs> {
  return getStructEncoder([
    ['sqrtPrice', getU128Encoder()],
    ['liquidity', getU128Encoder()],
  ]);
}

export function getLiquidityDistributionParametersDecoder(): Decoder<LiquidityDistributionParameters> {
  return getStructDecoder([
    ['sqrtPrice', getU128Decoder()],
    ['liquidity', getU128Decoder()],
  ]);
}

export function getLiquidityDistributionParametersCodec(): Codec<
  LiquidityDistributionParametersArgs,
  LiquidityDistributionParameters
> {
  return combineCodec(
    getLiquidityDistributionParametersEncoder(),
    getLiquidityDistributionParametersDecoder()
  );
}
