/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

/** Information regarding fee charges */
export type PoolFees = {
  tradeFeeNumerator: bigint;
  tradeFeeDenominator: bigint;
  protocolTradeFeeNumerator: bigint;
  protocolTradeFeeDenominator: bigint;
};

export type PoolFeesArgs = {
  tradeFeeNumerator: number | bigint;
  tradeFeeDenominator: number | bigint;
  protocolTradeFeeNumerator: number | bigint;
  protocolTradeFeeDenominator: number | bigint;
};

export function getPoolFeesEncoder(): Encoder<PoolFeesArgs> {
  return getStructEncoder([
    ['tradeFeeNumerator', getU64Encoder()],
    ['tradeFeeDenominator', getU64Encoder()],
    ['protocolTradeFeeNumerator', getU64Encoder()],
    ['protocolTradeFeeDenominator', getU64Encoder()],
  ]);
}

export function getPoolFeesDecoder(): Decoder<PoolFees> {
  return getStructDecoder([
    ['tradeFeeNumerator', getU64Decoder()],
    ['tradeFeeDenominator', getU64Decoder()],
    ['protocolTradeFeeNumerator', getU64Decoder()],
    ['protocolTradeFeeDenominator', getU64Decoder()],
  ]);
}

export function getPoolFeesCodec(): Codec<PoolFeesArgs, PoolFees> {
  return combineCodec(getPoolFeesEncoder(), getPoolFeesDecoder());
}
