/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type PoolMetrics = {
  totalProtocolBaseFee: bigint;
  totalProtocolQuoteFee: bigint;
  totalTradingBaseFee: bigint;
  totalTradingQuoteFee: bigint;
};

export type PoolMetricsArgs = {
  totalProtocolBaseFee: number | bigint;
  totalProtocolQuoteFee: number | bigint;
  totalTradingBaseFee: number | bigint;
  totalTradingQuoteFee: number | bigint;
};

export function getPoolMetricsEncoder(): Encoder<PoolMetricsArgs> {
  return getStructEncoder([
    ['totalProtocolBaseFee', getU64Encoder()],
    ['totalProtocolQuoteFee', getU64Encoder()],
    ['totalTradingBaseFee', getU64Encoder()],
    ['totalTradingQuoteFee', getU64Encoder()],
  ]);
}

export function getPoolMetricsDecoder(): Decoder<PoolMetrics> {
  return getStructDecoder([
    ['totalProtocolBaseFee', getU64Decoder()],
    ['totalProtocolQuoteFee', getU64Decoder()],
    ['totalTradingBaseFee', getU64Decoder()],
    ['totalTradingQuoteFee', getU64Decoder()],
  ]);
}

export function getPoolMetricsCodec(): Codec<PoolMetricsArgs, PoolMetrics> {
  return combineCodec(getPoolMetricsEncoder(), getPoolMetricsDecoder());
}
