/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from '@solana/kit';
import {
  getBaseFeeParametersDecoder,
  getBaseFeeParametersEncoder,
  getDynamicFeeParametersDecoder,
  getDynamicFeeParametersEncoder,
  type BaseFeeParameters,
  type BaseFeeParametersArgs,
  type DynamicFeeParameters,
  type DynamicFeeParametersArgs,
} from '.';

/** Information regarding fee charges */
export type PoolFeeParamters = {
  /** Base fee */
  baseFee: BaseFeeParameters;
  /** dynamic fee */
  dynamicFee: Option<DynamicFeeParameters>;
};

export type PoolFeeParamtersArgs = {
  /** Base fee */
  baseFee: BaseFeeParametersArgs;
  /** dynamic fee */
  dynamicFee: OptionOrNullable<DynamicFeeParametersArgs>;
};

export function getPoolFeeParamtersEncoder(): Encoder<PoolFeeParamtersArgs> {
  return getStructEncoder([
    ['baseFee', getBaseFeeParametersEncoder()],
    ['dynamicFee', getOptionEncoder(getDynamicFeeParametersEncoder())],
  ]);
}

export function getPoolFeeParamtersDecoder(): Decoder<PoolFeeParamters> {
  return getStructDecoder([
    ['baseFee', getBaseFeeParametersDecoder()],
    ['dynamicFee', getOptionDecoder(getDynamicFeeParametersDecoder())],
  ]);
}

export function getPoolFeeParamtersCodec(): Codec<
  PoolFeeParamtersArgs,
  PoolFeeParamters
> {
  return combineCodec(
    getPoolFeeParamtersEncoder(),
    getPoolFeeParamtersDecoder()
  );
}
