/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type SwapParameters = { amountIn: bigint; minimumAmountOut: bigint };

export type SwapParametersArgs = {
  amountIn: number | bigint;
  minimumAmountOut: number | bigint;
};

export function getSwapParametersEncoder(): Encoder<SwapParametersArgs> {
  return getStructEncoder([
    ['amountIn', getU64Encoder()],
    ['minimumAmountOut', getU64Encoder()],
  ]);
}

export function getSwapParametersDecoder(): Decoder<SwapParameters> {
  return getStructDecoder([
    ['amountIn', getU64Decoder()],
    ['minimumAmountOut', getU64Decoder()],
  ]);
}

export function getSwapParametersCodec(): Codec<
  SwapParametersArgs,
  SwapParameters
> {
  return combineCodec(getSwapParametersEncoder(), getSwapParametersDecoder());
}
