/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { VIRTUAL_CURVE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_CLAIM_FEE_OPERATOR_DISCRIMINATOR = new Uint8Array([
  38, 134, 82, 216, 95, 124, 17, 99,
]);

export function getCloseClaimFeeOperatorDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_CLAIM_FEE_OPERATOR_DISCRIMINATOR
  );
}

export type CloseClaimFeeOperatorInstruction<
  TProgram extends string = typeof VIRTUAL_CURVE_PROGRAM_ADDRESS,
  TAccountClaimFeeOperator extends string | IAccountMeta<string> = string,
  TAccountRentReceiver extends string | IAccountMeta<string> = string,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountEventAuthority extends string | IAccountMeta<string> = string,
  TAccountProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountClaimFeeOperator extends string
        ? WritableAccount<TAccountClaimFeeOperator>
        : TAccountClaimFeeOperator,
      TAccountRentReceiver extends string
        ? WritableAccount<TAccountRentReceiver>
        : TAccountRentReceiver,
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseClaimFeeOperatorInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseClaimFeeOperatorInstructionDataArgs = {};

export function getCloseClaimFeeOperatorInstructionDataEncoder(): Encoder<CloseClaimFeeOperatorInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLOSE_CLAIM_FEE_OPERATOR_DISCRIMINATOR,
    })
  );
}

export function getCloseClaimFeeOperatorInstructionDataDecoder(): Decoder<CloseClaimFeeOperatorInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseClaimFeeOperatorInstructionDataCodec(): Codec<
  CloseClaimFeeOperatorInstructionDataArgs,
  CloseClaimFeeOperatorInstructionData
> {
  return combineCodec(
    getCloseClaimFeeOperatorInstructionDataEncoder(),
    getCloseClaimFeeOperatorInstructionDataDecoder()
  );
}

export type CloseClaimFeeOperatorAsyncInput<
  TAccountClaimFeeOperator extends string = string,
  TAccountRentReceiver extends string = string,
  TAccountAdmin extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  claimFeeOperator: Address<TAccountClaimFeeOperator>;
  rentReceiver: Address<TAccountRentReceiver>;
  admin: TransactionSigner<TAccountAdmin>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
};

export async function getCloseClaimFeeOperatorInstructionAsync<
  TAccountClaimFeeOperator extends string,
  TAccountRentReceiver extends string,
  TAccountAdmin extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VIRTUAL_CURVE_PROGRAM_ADDRESS,
>(
  input: CloseClaimFeeOperatorAsyncInput<
    TAccountClaimFeeOperator,
    TAccountRentReceiver,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CloseClaimFeeOperatorInstruction<
    TProgramAddress,
    TAccountClaimFeeOperator,
    TAccountRentReceiver,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VIRTUAL_CURVE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    claimFeeOperator: {
      value: input.claimFeeOperator ?? null,
      isWritable: true,
    },
    rentReceiver: { value: input.rentReceiver ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.claimFeeOperator),
      getAccountMeta(accounts.rentReceiver),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getCloseClaimFeeOperatorInstructionDataEncoder().encode({}),
  } as CloseClaimFeeOperatorInstruction<
    TProgramAddress,
    TAccountClaimFeeOperator,
    TAccountRentReceiver,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >;

  return instruction;
}

export type CloseClaimFeeOperatorInput<
  TAccountClaimFeeOperator extends string = string,
  TAccountRentReceiver extends string = string,
  TAccountAdmin extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  claimFeeOperator: Address<TAccountClaimFeeOperator>;
  rentReceiver: Address<TAccountRentReceiver>;
  admin: TransactionSigner<TAccountAdmin>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
};

export function getCloseClaimFeeOperatorInstruction<
  TAccountClaimFeeOperator extends string,
  TAccountRentReceiver extends string,
  TAccountAdmin extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof VIRTUAL_CURVE_PROGRAM_ADDRESS,
>(
  input: CloseClaimFeeOperatorInput<
    TAccountClaimFeeOperator,
    TAccountRentReceiver,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CloseClaimFeeOperatorInstruction<
  TProgramAddress,
  TAccountClaimFeeOperator,
  TAccountRentReceiver,
  TAccountAdmin,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? VIRTUAL_CURVE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    claimFeeOperator: {
      value: input.claimFeeOperator ?? null,
      isWritable: true,
    },
    rentReceiver: { value: input.rentReceiver ?? null, isWritable: true },
    admin: { value: input.admin ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.claimFeeOperator),
      getAccountMeta(accounts.rentReceiver),
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getCloseClaimFeeOperatorInstructionDataEncoder().encode({}),
  } as CloseClaimFeeOperatorInstruction<
    TProgramAddress,
    TAccountClaimFeeOperator,
    TAccountRentReceiver,
    TAccountAdmin,
    TAccountEventAuthority,
    TAccountProgram
  >;

  return instruction;
}

export type ParsedCloseClaimFeeOperatorInstruction<
  TProgram extends string = typeof VIRTUAL_CURVE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    claimFeeOperator: TAccountMetas[0];
    rentReceiver: TAccountMetas[1];
    admin: TAccountMetas[2];
    eventAuthority: TAccountMetas[3];
    program: TAccountMetas[4];
  };
  data: CloseClaimFeeOperatorInstructionData;
};

export function parseCloseClaimFeeOperatorInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCloseClaimFeeOperatorInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      claimFeeOperator: getNextAccount(),
      rentReceiver: getNextAccount(),
      admin: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getCloseClaimFeeOperatorInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
